Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -35,24 +35,24 @@ jobs:
         shell: bash
 
       - name: Build geosite.dat file
-		  run: |
-			cd code || exit 1
-
-			# Create data directory
-			mkdir -p data
-
-			# Download domain list from GitHub and save to tenmien.txt
-			curl -sSL https://raw.githubusercontent.com/Thaomtam/Geosite-vn/rule-set/tenmien.json > data/tenmien.txt
-
-			# Copy tenmien.txt to category-ads-all
-			cp data/tenmien.txt data/category-ads-all
-
-			# Run go script to build geosite.dat
-			go run ./ --outputdir=../ --exportlists=category-ads-all --datapath=data
-
-			# Cleanup and finalize
-			cd ../ && rm -rf code
-			mv dlc.dat geosite.dat
+        run: |
+          cd code || exit 1
+          
+          # Create data directory
+          mkdir -p data
+          
+          # Download domain list from GitHub and save to tenmien.txt
+          curl -sSL https://raw.githubusercontent.com/Thaomtam/Geosite-vn/rule-set/tenmien.json > data/tenmien.txt
+          
+          # Copy tenmien.txt to category-ads-all
+          cp data/tenmien.txt data/category-ads-all
+          
+          # Run go script to build geosite.dat
+          go run ./ --outputdir=../ --exportlists=category-ads-all --datapath=data
+          
+          # Cleanup and finalize
+          cd ../ && rm -rf code
+          mv dlc.dat geosite.dat
 
       - name: Generate geosite.dat sha256 hash
         run: |
