Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -35,14 +35,41 @@ jobs:
         shell: bash
 
       - name: Build geosite.dat file
-	  run: |
-	    cd code || exit 1
-	    mkdir -p data
-	    curl -sSL https://raw.githubusercontent.com/Thaomtam/Geosite-vn/rule-set/tenmien.json > data/tenmien.txt
-	    cat data/tenmien.txt | sort | uniq > data/category-ads-all
-	    go run ./build.go --outputdir=../ --exportlists=category-ads-all --datapath=data
-	    cd ../ && rm -rf code
-	    mv dlc.dat geosite.dat
+        run: |
+          cd code || exit 1
+          
+          # Create data directory
+          mkdir -p data
+          
+          # Download domain list from GitHub
+          curl -sSL https://raw.githubusercontent.com/Thaomtam/Geosite-vn/rule-set/tenmien.json > data/tenmien.txt
+          
+          # Download and process ad blocking lists
+          curl -sSL https://easylist-downloads.adblockplus.org/easylist.txt \
+            | perl -ne '/^\|\|([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})\^$/ && print "$1\n"' \
+            | perl -ne 'print if not /^[0-9]{1,3}(\.[0-9]{1,3}){3}$/' > data/easylist.txt
+          
+          curl -sSL https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt \
+            | perl -ne '/^\|\|([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})\^$/ && print "$1\n"' \
+            | perl -ne 'print if not /^[0-9]{1,3}(\.[0-9]{1,3}){3}$/' > data/adguard_dns.txt
+          
+          curl -sSL https://someonewhocares.org/hosts/hosts \
+            | perl -ne '/^127\.0\.0\.1\s([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})/ && print "$1\n"' \
+            | sed '1d' >> data/DANPOLLOCK.txt
+          
+          curl -sSL https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext \
+            | perl -ne '/^127\.0\.0\.1\s([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})$/ && print "$1\n"' > data/PETERLOWE.txt
+          
+          # Merge all lists into category-ads-all and remove duplicates
+          cat data/tenmien.txt data/easylist.txt data/adguard_dns.txt data/DANPOLLOCK.txt data/PETERLOWE.txt \
+            | sort | uniq > data/category-ads-all
+          
+          # Run go script to build geosite.dat
+          go run ./ --outputdir=../ --exportlists=category-ads-all --datapath=data
+          
+          # Cleanup and finalize
+          cd ../ && rm -rf code
+          mv dlc.dat geosite.dat
 
       - name: Generate geosite.dat sha256 hash
         run: |
